CREATE DATABASE TRABALHOPHP;
USE TRABALHOPHP;

CREATE TABLE USUARIO(
	id INT AUTO_INCREMENT PRIMARY KEY,
    Email VARCHAR(255) NOT NULL,
    Nome VARCHAR(255) NOT NULL,
    CPF VARCHAR(18) NOT NULL,
    Senha VARCHAR(255) NOT NULL
);
